//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLuong
    {
        public string CMND { get; set; }
        public Nullable<int> Ngay { get; set; }
        public Nullable<decimal> LuongCB { get; set; }
        public Nullable<double> HeSo { get; set; }
        public Nullable<decimal> Trocap { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
