//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenhBenhNhan
    {
        public int ID { get; set; }
        public string IDBenhNhan { get; set; }
        public Nullable<int> IDBenh { get; set; }
    
        public virtual LoaiBenh LoaiBenh { get; set; }
        public virtual BenhNhan BenhNhan { get; set; }
    }
}
