//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonThuoc
    {
        public Nullable<int> IDThuoc { get; set; }
        public string IDBenhNhan { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual LoaiThuoc LoaiThuoc { get; set; }
    }
}
