//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuongCoBan
    {
        public string Ngạch { get; set; }
        public Nullable<double> Hạng_I { get; set; }
        public Nullable<double> Hạng_II { get; set; }
        public Nullable<double> Hạng_III { get; set; }
    }
}
