//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhVien
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyBenhVienEntities : DbContext
    {
        public QuanLyBenhVienEntities()
            : base("name=QuanLyBenhVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangLuong> BangLuongs { get; set; }
        public virtual DbSet<BenhNhan> BenhNhans { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<DonThuoc> DonThuocs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<LoaiBenh> LoaiBenhs { get; set; }
        public virtual DbSet<LoaiThuoc> LoaiThuocs { get; set; }
        public virtual DbSet<LuongCoBan> LuongCoBans { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int AddLuongNhanVien(string cMND, Nullable<decimal> luongCB, Nullable<double> heSo, Nullable<decimal> trocap)
        {
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var luongCBParameter = luongCB.HasValue ?
                new ObjectParameter("LuongCB", luongCB) :
                new ObjectParameter("LuongCB", typeof(decimal));
    
            var heSoParameter = heSo.HasValue ?
                new ObjectParameter("HeSo", heSo) :
                new ObjectParameter("HeSo", typeof(double));
    
            var trocapParameter = trocap.HasValue ?
                new ObjectParameter("Trocap", trocap) :
                new ObjectParameter("Trocap", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddLuongNhanVien", cMNDParameter, luongCBParameter, heSoParameter, trocapParameter);
        }
    
        public virtual int AddNhanVien(string cMND, string ten, Nullable<System.DateTime> ngaySinh, string gioiTinh, Nullable<int> ex, string diaChi, string quocTich, string sDT, Nullable<int> iDchucvu, string hang, Nullable<int> bac)
        {
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var exParameter = ex.HasValue ?
                new ObjectParameter("Ex", ex) :
                new ObjectParameter("Ex", typeof(int));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var quocTichParameter = quocTich != null ?
                new ObjectParameter("QuocTich", quocTich) :
                new ObjectParameter("QuocTich", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var iDchucvuParameter = iDchucvu.HasValue ?
                new ObjectParameter("IDchucvu", iDchucvu) :
                new ObjectParameter("IDchucvu", typeof(int));
    
            var hangParameter = hang != null ?
                new ObjectParameter("Hang", hang) :
                new ObjectParameter("Hang", typeof(string));
    
            var bacParameter = bac.HasValue ?
                new ObjectParameter("Bac", bac) :
                new ObjectParameter("Bac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddNhanVien", cMNDParameter, tenParameter, ngaySinhParameter, gioiTinhParameter, exParameter, diaChiParameter, quocTichParameter, sDTParameter, iDchucvuParameter, hangParameter, bacParameter);
        }
    
        public virtual int DeleteLuongNhanVien(string cMND)
        {
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteLuongNhanVien", cMNDParameter);
        }
    
        public virtual int DeleteNhanVien(string cMND)
        {
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteNhanVien", cMNDParameter);
        }
    
        public virtual int EditLuongNhanVien(string cMND, Nullable<decimal> luongCB, Nullable<double> heSo, Nullable<decimal> trocap)
        {
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var luongCBParameter = luongCB.HasValue ?
                new ObjectParameter("LuongCB", luongCB) :
                new ObjectParameter("LuongCB", typeof(decimal));
    
            var heSoParameter = heSo.HasValue ?
                new ObjectParameter("HeSo", heSo) :
                new ObjectParameter("HeSo", typeof(double));
    
            var trocapParameter = trocap.HasValue ?
                new ObjectParameter("Trocap", trocap) :
                new ObjectParameter("Trocap", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditLuongNhanVien", cMNDParameter, luongCBParameter, heSoParameter, trocapParameter);
        }
    
        public virtual int EditNhanVien(string cMND, string ten, Nullable<System.DateTime> ngaySinh, string gioiTinh, Nullable<int> ex, string diaChi, string quocTich, string sDT, Nullable<int> iDchucvu, string hang, Nullable<int> bac)
        {
            var cMNDParameter = cMND != null ?
                new ObjectParameter("CMND", cMND) :
                new ObjectParameter("CMND", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var exParameter = ex.HasValue ?
                new ObjectParameter("Ex", ex) :
                new ObjectParameter("Ex", typeof(int));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var quocTichParameter = quocTich != null ?
                new ObjectParameter("QuocTich", quocTich) :
                new ObjectParameter("QuocTich", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var iDchucvuParameter = iDchucvu.HasValue ?
                new ObjectParameter("IDchucvu", iDchucvu) :
                new ObjectParameter("IDchucvu", typeof(int));
    
            var hangParameter = hang != null ?
                new ObjectParameter("Hang", hang) :
                new ObjectParameter("Hang", typeof(string));
    
            var bacParameter = bac.HasValue ?
                new ObjectParameter("Bac", bac) :
                new ObjectParameter("Bac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditNhanVien", cMNDParameter, tenParameter, ngaySinhParameter, gioiTinhParameter, exParameter, diaChiParameter, quocTichParameter, sDTParameter, iDchucvuParameter, hangParameter, bacParameter);
        }
    
        public virtual ObjectResult<GetLuongCoBan_Result> GetLuongCoBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLuongCoBan_Result>("GetLuongCoBan");
        }
    
        public virtual ObjectResult<GetSalaryTableAndName_Result> GetSalaryTableAndName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSalaryTableAndName_Result>("GetSalaryTableAndName");
        }
    
        public virtual ObjectResult<GetStaffNSalaryAndTable_Result> GetStaffNSalaryAndTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStaffNSalaryAndTable_Result>("GetStaffNSalaryAndTable");
        }
    }
}
